### ISSUE TITLE
Add missing ConfigDrive support

### ISSUE THREAD

**Issue by sleinen** [switch-ch/diskimage-builder#8]
The images that we build for SWITCHengines users are currently configured to use only the `Ec2` data source.  This is configured (at least on Debian/Ubuntu) in `/etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg`, which includes something like

```
datasource_list: [  Ec2, None ]
```

Some users may want to use `ConfigDrive` as a data source instead.  Possible reasons include paranoia (the unsecured HTTP-over-IPv4 access to the metadata server might be intercepted), or the fact that IPv6-only instances cannot access the metadata server at all.  Therefore it would seem better to change the default to e.g.

```
datasource_list: [  ConfigDrive, Ec2, None ]
```

For those users who _don't_ user config drives (that is the vast majority of users now), this shouldn't change anything.  The hope is that cloud-init will _quickly and discreetly_ (e.g. without generating scary error messages) determine that no `ConfigDrive` source is present, and fall back to the usual `Ec2` data source.  That would need to be verified.

**Comment by sleinen** [comment]
There are other possible reasons to use config drives: For example, a user may not trust our network-based (HTTP) metadata service... with some reason, because in the past, we sometimes had trouble with DHCP or metadata servers.  Config drives make them immune against those issues.

**Comment by valerytschopp** [comment]
Setting the variable 
```
DIB_CLOUD_INIT_DATASOURCES="Ec2, ConfigDrive"
``` 
or 
```
DIB_CLOUD_INIT_DATASOURCES="ConfigDrive, Ec2"
```
in the correct [env_source](https://github.com/switch-ch/diskimage-builder/tree/SWITCHengines/env_source) files will magically generate the `/etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg` file

**Comment by valerytschopp** [comment]
Commit aa22c0d11fb41b0cf0b72b9a485e9e438f8d3ca7 should fix this issue and enable both `Ec2` and `ConfigDrive` for the cloud-init datasources.
